### ISSUE TITLE
Add token indexer resource for builders

### ISSUE THREAD

**Issue by Heisenburgirs** [lukso-network/awesome-lukso#1]
Our open-source LSP token indexer might be helpful for new builders to get into Lukso or indexing in general

https://github.com/Deliquified/lsp-token-indexer

**Comment by CJ42** [comment]
Thanks @Heisenburgirs, added in the list ✅

https://github.com/lukso-network/awesome-lukso/commit/bb944263dff312c9ab3f432c2d1462bd0e9d2d2c
